--[[
This file was extracted by 'EsoLuaGenerator' at '2021-09-04 16:42:27' using the latest game version.
NOTE: This file should only be used as IDE support; it should NOT be distributed with addons!

****************************************************************************
           CONTENTS OF THIS FILE IS COPYRIGHT ZENIMAX MEDIA INC.
****************************************************************************
]]

KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_VIDEO, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_VIDEO))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_AUDIO, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_AUDIO))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_GAMEPLAY, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_GAMEPLAY))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_CAMERA, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_CAMERA))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_INTERFACE, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_INTERFACE))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_NAMEPLATES, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_NAMEPLATES))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_SOCIAL, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_SOCIAL))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_COMBAT, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_COMBAT))
