--[[
This file was extracted by 'EsoLuaGenerator' at '2021-09-04 16:42:27' using the latest game version.
NOTE: This file should only be used as IDE support; it should NOT be distributed with addons!

****************************************************************************
           CONTENTS OF THIS FILE IS COPYRIGHT ZENIMAX MEDIA INC.
****************************************************************************
]]

--------------------------------
--Gamepad Voice Chat Scenes
--------------------------------
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.GAMEPAD_DRIVEN_UI_WINDOW)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_GAMEPAD_RIGHT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(MINIMIZE_CHAT_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_MENU_SOUND_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_VOICECHAT_CHANNELS_FRAGMENT)

GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.GAMEPAD_DRIVEN_UI_WINDOW)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_GAMEPAD_RIGHT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(MINIMIZE_CHAT_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_MENU_SOUND_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_VOICECHAT_PARTICIPANTS_FRAGMENT)
